package blockly;

import javafx.scene.web.WebEngine;

/**
 * Represents Blockly instance.
 */
public class Blockly {

    private WebEngine webEngine = null;

    // takes webEngine to start blockly in
    public Blockly(WebEngine webEngine) throws IllegalArgumentException {
        if (webEngine == null) throw new IllegalArgumentException();
        this.webEngine = webEngine;
        this.webEngine.load(getClass().getResource("/google-blockly/blockly_main_page.html").toString());
    }

    // returns code generated by blockly
    public String getCode() {
        if (webEngine == null) return "ERROR: No webengine found.";
        return (String) webEngine.executeScript("Blockly.basicOttoGenerator.workspaceToCode(workspace)");
    }



}
